### ISSUE TITLE
vaapi-fits doesn't work

### ISSUE THREAD

**Issue by xhaihao** [intel/vaapi-fits#116]
Command:
`LIBVA_DRIVER_NAME=iHD vaapi-fits run test/gst-msdk/vpp/rotation.py --platform KBL -k degrees=90 -vv`

Error:
> Traceback (most recent call last):
  File "./vaapi-fits", line 11, in <module>
    from slash.frontend.main import main_entry_point
  File "/usr/local/lib/python2.7/dist-packages/slash/__init__.py", line 6, in <module>
    from .core.session import Session
  File "/usr/local/lib/python2.7/dist-packages/slash/core/session.py", line 16, in <module>
    from .fixtures.fixture_store import FixtureStore
  File "/usr/local/lib/python2.7/dist-packages/slash/core/fixtures/fixture_store.py", line 6, in <module>
    from orderedset import OrderedSet
  File "/usr/local/lib/python2.7/dist-packages/orderedset/__init__.py", line 5, in <module>
    from ._orderedset import OrderedSet
ImportError: /usr/local/lib/python2.7/dist-packages/orderedset/_orderedset.so: undefined symbol: PyFPE_jbuf

**Comment by uartie** [comment]
What distro are you using? It seems others have had similar issues when using pip vs. system package manager to install python modules.  The problem seems to be multiple versions of python module installed by different package manager.  Can you check if the python orderedset module (and other modules) is installed twice (one by system package manager and one by pip)?  If so, please uninstall the one by system package manager and then force reinstall with pip.

**Comment by xhaihao** [comment]
I am using Ubuntu 18.10.
How can I check whether the orderedset module is installed twice?
$> dpkg -l | grep orderedset
$> pip list --format legacy  | grep orderedset
orderedset (2.0.1)

**Comment by uartie** [comment]
Yes, I think dpkg and pip are the right methods for checking versions on ubuntu.  I don't think apt provides a orderedset package, though.

Maybe you can try force reinstall with pip like so:
```
sudo pip install -U --force-reinstall --no-cache-dir numpy scikit-image slash==1.5.1
```
This should reinstall orderedset dependency along with others.

**Comment by xhaihao** [comment]
Thanks for the help ! It works after reinstalling the packages.
