### ISSUE TITLE
do we need more than one suit of reference psnr

### ISSUE THREAD

**Issue by zhuqingliang** [intel/vaapi-fits#75]
./full run test/ffmpeg-vaapi/encode/avc.py -k bframes=0,case=4k2013,gop=30,profile=main,qp=51,quality=1,slices=3
on ICL:
psnr =  25.6864, 39.3725, 39.5874, 28.0653, 41.1952, 40.7418
on KBL:
psnr =  26.8123, 38.7912, 38.7007, 28.5433, 40.9245, 40.3934

use one as reference then the other will fail.

**Comment by zhuqingliang** [comment]
Yes ,  the PSNR are the same every time . I think it's not a R2R issue. @lizhong1008   Can you give a comment?

**Comment by uartie** [comment]
Are the PSNR's different when comparing gstreamer runs on KBL vs. ICL?

**Comment by zhuqingliang** [comment]
run the same case
ffmpeg-qsv
----------------------
ICL ： 25.6564, 39.3784, 40.1553, 30.1983, 41.9603, 42.2321
KBL ：26.9046, 38.807, 38.9301, 30.7088, 41.6305, 41.7316

gst-vaapi
---------------------
ICL :   25.6864, 39.3715, 39.6011, 28.0653, 41.1934, 40.7443
KBL  : 26.8123, 38.794, 38.7266, 28.5433, 40.9229, 40.4032

gst-msdk
--------------------
ICL :  25.6511, 39.3511, 40.3076, 33.4652, 45.7268, 46.4823
KBL :  26.9368, 38.9324, 39.2732, 34.0295, 45.3923, 46.0265

seems have similar phenomena

**Comment by uartie** [comment]
@zhuqingliang thanks for the info.  Are there a lot of test cases failing due to this phenomena?  Does it only happen with specific encode parameter settings (e.g. slices=3 and/or profile=main, etc)?

There would be high maintenance overhead to manage separate PSNR reference files on a per-platform basis.  So if we can avoid that, it would be ideal.  Maybe we can increase the PSNR tolerance on a per-case basis?

@lizhong1008 can you check with driver team about expectations for ICL vs KBL quality differences?

**Comment by zhuqingliang** [comment]
this two parameter also have this phenomena. 
cqp/test(bframes=0,case=4k2013,gop=30,profile=main,qp=51,quality=1,slices=3
cqp/test(bframes=0,case=480p,gop=100,profile=main,qp=51,quality=4,slices=1
and reference + 0.2 is good for most of the case.  These case with the same 
phenomena are less than 1% in all test, maybe we can just adjust the ref to fit most of the platform.

**Comment by uartie** [comment]
Please move this issue to internal suite repo as it only relates to those cases/references.  We can discuss more there.
